### ISSUE TITLE
golang 기초문법

### ISSUE THREAD

**Issue by opklnm102** [opklnm102/study#6]
golang 기초문법 공부해서 정리하기

**Comment by opklnm102** [comment]
[go 디렉토리](https://github.com/opklnm102/study/tree/master/go)에서 정리 중

**Comment by opklnm102** [comment]
go tour 완료

**Comment by kidkkr** [comment]
동희님 golang은 스터디로 하고 계신건가요? ㄷㄷ

**Comment by opklnm102** [comment]
혼자하고 있어요~_~

**Comment by kidkkr** [comment]
네넵 당장은(?) 그때 해커톤 이후로 회사에서 일하게 되서 여유가 안되지만 함께하고 싶네요ㅎㅎ 일단 팔로하고 있겠습니다!

**Comment by opklnm102** [comment]
오호 축하드립니다~
